import Product from '../../components/ui/product'
import ProductList from '../../components/ui/product-list'

const gastro = [
	{
		id: 1,
		name: 'Стейк лосося с овошами',
		img: 'dish1.webp',
		category: 'Горячие блюда',
		structure: '~',
		price: '27.00',
		weight: '400',
	},
	{
		id: 2,
		name: 'Морской окунь',
		img: 'dish3.webp',
		category: 'Горячие блюда',
		structure: '~',
		price: '16.00',
		weight: '170',
	},
	{
		id: 3,
		name: 'Баварская колбаска с соусом',
		img: 'dish22.webp',
		category: 'Горячие блюда',
		structure: '~',
		price: '25.00',
		weight: '550',
	},
	{
		id: 4,
		name: 'Венский шницель',
		img: 'dish23.webp',
		category: 'Горячие блюда',
		structure: 'свиное филе, картофель, салат овощной',
		price: '18.00',
		weight: '430',
	},
	{
		id: 5,
		name: "Доска 'Пивной расколбас'",
		img: 'dish24.webp',
		category: 'Горячие блюда',
		structure: 'ассорти из гриль колбасок, картофель, овощи и соус',
		price: '19.00',
		weight: '260/230/60',
	},
	{
		id: 6,
		name: "Патэльня 'Вясковы Luxury Style №1'",
		img: 'dish25.webp',
		category: 'Горячие блюда',
		structure: 'колбаса домашняя, бекон, картофель, грибы, яйцо',
		price: '17.00',
		weight: '360',
	},
	{
		id: 8,
		name: "Патэльня 'Дзеруны па-Палескi'",
		img: 'dish26.webp',
		category: 'Горячие блюда',
		structure: 'драники с мачанкой',
		price: '19.00',
		weight: '500',
	},
	{
		id: 9,
		name: "Патэльня 'Cыты Дзядзька'",
		img: 'dish27.webp',
		category: 'Горячие блюда',
		structure: 'свиное филе, картофель, соус',
		price: '18.00',
		weight: '350/25',
	},
	{
		id: 10,
		name: 'Патэльня Креветки в чесночном соусе',
		img: 'dish2.webp',
		category: 'Горячие блюда',
		structure: '~',
		price: '27.00',
		weight: '400',
	},
	{
		id: 11,
		name: 'Ребра в соусе Djack Daniels',
		img: 'dish28.webp',
		category: 'Горячие блюда',
		structure: 'запеченные ребра, овоши, соус',
		price: '27.00',
		weight: '530',
	},
	{
		id: 12,
		name: 'Шашлык',
		img: 'dish38.webp',
		category: 'Горячие блюда',
		structure: '~',
		price: '40.00',
		weight: '900',
	},
	{
		id: 13,
		name: 'Пицца Мюнхенская',
		img: 'dish4.webp',
		category: 'Пиццы',
		structure:
			'охотничьи колбаски, салями, марин. огурец, горчичный соус, сыр Моцарелла',
		price: '19.00',
		weight: '600',
	},
	{
		id: 14,
		name: 'Пицца Панчетта Чиполло',
		img: 'dish5.webp',
		category: 'Пиццы',
		structure: 'бекон, маринованный огурец, красный лук, сыр Моцарелла',
		price: '18.00',
		weight: '550',
	},
	{
		id: 15,
		name: 'Пицца Хмельная Пробка',
		img: 'dish6.webp',
		category: 'Пиццы',
		structure:
			'ветчина, салями, грибы, перец сладкий, соус барбекю, сыр Моцарелла',
		price: '19.00',
		weight: '600',
	},
	{
		id: 16,
		name: 'Пицца Валенсия',
		img: 'dish13.webp',
		category: 'Пиццы',
		structure: 'лосось, черри, сыр Фета, сыр Моцарелла, айсберг',
		price: '19.00',
		weight: '550',
	},
	{
		id: 17,
		name: 'Пицца LA PARMA',
		img: 'dish36.webp',
		category: 'Пиццы',
		structure: '~',
		price: '17.00',
		weight: '400',
	},
	{
		id: 18,
		name: 'Пицца Грибная',
		img: 'dish39.webp',
		category: 'Пиццы',
		structure: '~',
		price: '19.00',
		weight: '400',
	},
	{
		id: 19,
		name: 'Гренки чесночные с соусом',
		img: 'dish7.webp',
		category: 'Гарниры и Закуски',
		structure: '~',
		price: '5.00',
		weight: '125/30',
	},
	{
		id: 20,
		name: 'Картофель фри с соусом',
		img: 'dish8.webp',
		category: 'Гарниры и Закуски',
		structure: '~',
		price: '4.50',
		weight: '110/30',
	},
	{
		id: 21,
		name: 'Балтийская салака',
		img: 'dish14.webp',
		category: 'Гарниры и Закуски',
		structure: '~',
		price: '5.50',
		weight: '150',
	},
	{
		id: 22,
		name: 'Луковые кольца с соусом',
		img: 'dish17.webp',
		category: 'Гарниры и Закуски',
		structure: '~',
		price: '7.50',
		weight: '150/30',
	},
	{
		id: 23,
		name: 'Свиные уши с соусом',
		img: 'dish18.webp',
		category: 'Гарниры и Закуски',
		structure: '~',
		price: '9.00',
		weight: '200/30',
	},
	{
		id: 24,
		name: 'Сырные палочки с соусом',
		img: 'dish19.webp',
		category: 'Гарниры и Закуски',
		structure: '~',
		price: '15.00',
		weight: '150/30',
	},
	{
		id: 25,
		name: 'Тако с рваной свининой',
		img: 'dish20.webp',
		category: 'Гарниры и Закуски',
		structure: '~',
		price: '14.00',
		weight: '310/30',
	},
	{
		id: 26,
		name: 'Крылышки в хрустяшей острой панировке с соусом',
		img: 'dish15.webp',
		category: 'Гарниры и Закуски',
		structure: '~',
		price: '25.00',
		weight: '400',
	},
	{
		id: 27,
		name: 'Куриные наггетсы с картофелем фри и соусом',
		img: 'dish16.webp',
		category: 'Гарниры и Закуски',
		structure: '~',
		price: '15.00',
		weight: '280',
	},
	{
		id: 28,
		name: 'Фишки к пиву из свиной грудинки',
		img: 'dish37.webp',
		category: 'Гарниры и Закуски',
		structure: '~',
		price: '12.50',
		weight: '200/50',
	},
	{
		id: 29,
		name: 'Сет №1 к пиву',
		img: 'dish10.webp',
		category: 'Ланч-Cеты',
		structure:
			'гренки, наггетсы, крылья в острой панировке, луковые кольца, картофель фри, 3 соуса',
		price: '29.00',
		weight: '650',
	},
	{
		id: 30,
		name: 'Сет №2 Немо',
		img: 'dish11.webp',
		category: 'Ланч-Cеты',
		structure: 'ассорти сухой и копчёной рыбы',
		price: '42.00',
		weight: '250',
	},
	{
		id: 31,
		name: 'Сет №3 Fishka',
		img: 'dish11.webp',
		category: 'Ланч-Cеты',
		structure: 'ассорти сухой и копчёной рыбы',
		price: '25.00',
		weight: '250',
	},
	{
		id: 32,
		name: 'Сет №4 Михалыч',
		img: 'dish12.webp',
		category: 'Ланч-Cеты',
		structure: 'ассорти из колбас, сала и овощей с соусом',
		price: '14.50',
		weight: '280',
	},
	{
		id: 33,
		name: 'Бургер с говядиной и беконом',
		img: 'dish29.webp',
		category: 'Бургеры',
		structure: '~',
		price: '20.00',
		weight: '450/100/30',
	},
	{
		id: 34,
		name: 'Бургер с курицей',
		img: 'dish30.webp',
		category: 'Бургеры',
		structure: '~',
		price: '20.00',
		weight: '450/100/30',
	},
	{
		id: 35,
		name: 'Венский штрудель',
		img: 'dish32.webp',
		category: 'Десерты',
		structure: '~',
		price: '7.00',
		weight: '170',
	},
	{
		id: 36,
		name: "Чизкейк 'Нью-Йорк'",
		img: 'dish33.webp',
		category: 'Десерты',
		structure: '~',
		price: '7.00',
		weight: '100',
	},
	{
		id: 37,
		name: 'Мороженое',
		img: 'dish34.webp',
		category: 'Десерты',
		structure: '~',
		price: '8.00',
		weight: '200',
	},
	{
		id: 38,
		name: 'Молочный коктейль',
		img: 'dish35.webp',
		category: 'Десерты',
		structure: '~',
		price: '8.00',
		weight: '500',
	},
];

const Gastropub = () => {
	return (
		<section className='grid grid-cols-2 h-full'>
			<Product item={gastro[0]} />
			<ProductList item={gastro} />
		</section>
	);
};

export default Gastropub;
