import type { Metadata } from 'next'
import Header from '../components/screen/header'
import './globals.css'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='ru'>
			<body className='max-w-screen-xl mx-auto flex flex-col relative overflow-x-hidden overflow-y-hidden'>
				<Header />
				{children}
			</body>
		</html>
	);
}
